### ISSUE TITLE
ignoreTargets demo missing?

### ISSUE THREAD

**Issue by jot6000** [aurbano/react-ds#9]
Hi there,

While trying to use this I am stumped at how to use ignoreTargets for a Selection.

I don't seem to understand what you mean by an 'array of css3 selectors'.

Some kind of code example showing how to create this would be very helpful as the only time I see it used is in the example.js, where you pass it from props and I cant see how the array should be created.

I apologise if this is not where I should ask such a question but I am at a loss for any other way of asking.

**Comment by aurbano** [comment]
Hey!

Good point I'll improve the docs 👍 

What it means is that you can pass an array of strings that are valid css selectors. For example:

```js
['.someClass', '#someId', 'div > .withChild']
```
